"""empty message

Revision ID: 81cfee8ca00c
Revises: 
Create Date: 2018-11-30 19:55:26.398034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81cfee8ca00c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=64), nullable=True),
    sa.Column('texto', sa.String(length=512), nullable=True),
    sa.Column('situacao', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('is_prof', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('autores_do_resumo',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('resumo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resumo_id'], ['resumos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'resumo_id')
    )
    op.create_table('avaliadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliador', sa.Integer(), nullable=True),
    sa.Column('resumo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avaliador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['resumo'], ['resumos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliadores')
    op.drop_table('autores_do_resumo')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('resumos')
    # ### end Alembic commands ###
