"""empty message

Revision ID: 9c6deb20b760
Revises: 0ef0a30e6c19
Create Date: 2018-11-30 09:35:00.823284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6deb20b760'
down_revision = '0ef0a30e6c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliador', sa.Integer(), nullable=True),
    sa.Column('resumo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avaliador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['resumo'], ['resumos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliadores')
    # ### end Alembic commands ###
