"""empty message

Revision ID: fef611456d68
Revises: 9c6deb20b760
Create Date: 2018-11-30 19:40:28.229336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef611456d68'
down_revision = '9c6deb20b760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumos', type_='foreignkey')
    op.drop_column('resumos', 'autor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumos', sa.Column('autor', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'resumos', 'usuarios', ['autor'], ['id'])
    # ### end Alembic commands ###
